# Generated by Django 5.2.4 on 2025-08-04 03:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TeacherDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("phone", models.CharField(max_length=100, unique=True)),
                ("address", models.CharField(max_length=100)),
                ("date_of_birth", models.DateField()),
                ("gender", models.CharField(max_length=100)),
                ("blood_group", models.CharField(max_length=100)),
                (
                    "profile_picture",
                    models.ImageField(
                        blank=True, null=True, upload_to="TeacherProfilePicture"
                    ),
                ),
                ("designation", models.CharField(max_length=100)),
                ("department", models.CharField(max_length=100)),
                ("is_hod", models.BooleanField(default=False)),
                ("is_placement_faculty", models.BooleanField(default=False)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
