# Generated by Django 5.2.4 on 2025-08-05 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("teacher", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="teacherdetails",
            name="department",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="teacherdetails",
            name="designation",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
