# Generated by Django 5.2.5 on 2025-08-11 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0002_alter_teacherdetails_department_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherdetails',
            name='specialization',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
