# Generated by Django 5.2.5 on 2025-08-18 10:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0004_alter_teacherdetails_address_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacherdetails',
            name='profile_picture',
            field=models.ImageField(blank=-2, null=True, upload_to='TeacherProfilePicture'),
        ),
        migrations.AlterField(
            model_name='teacherdetails',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teacher', to=settings.AUTH_USER_MODEL),
        ),
    ]
