# Generated by Django 5.2.5 on 2025-08-21 05:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0005_alter_teacherdetails_profile_picture_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Training',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('vedio', models.FileField(blank=True, null=True, upload_to='training_vedio')),
                ('quize', models.FileField(blank=True, null=True, upload_to='training_quize')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='training', to='teacher.teacherdetails')),
            ],
        ),
    ]
