# Generated by Django 5.2.5 on 2025-12-27 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0006_training'),
    ]

    operations = [
        migrations.AddField(
            model_name='training',
            name='gogle_meet_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
