# Generated by Django 5.2.5 on 2025-12-27 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0007_training_gogle_meet_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='training',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
