# Generated by Django 5.2.5 on 2026-01-09 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0008_training_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='training',
            name='google_form_link',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
