# Generated by Django 5.2.5 on 2026-01-09 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0009_training_google_form_link'),
    ]

    operations = [
        migrations.RenameField(
            model_name='training',
            old_name='google_form_link',
            new_name='quiz_link',
        ),
        migrations.RemoveField(
            model_name='training',
            name='quize',
        ),
    ]
