# Generated by Django 5.2.5 on 2025-12-31 08:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_notification_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='app.principal'),
        ),
    ]
