# Generated by Django 5.2.5 on 2025-08-22 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_studentdetails_company_studentdetails_job_location_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentdetails',
            old_name='company',
            new_name='company_location',
        ),
        migrations.RenameField(
            model_name='studentdetails',
            old_name='job_location',
            new_name='company_name',
        ),
    ]
