# Generated by Django 5.2.5 on 2025-08-22 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_rename_company_studentdetails_company_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentdetails',
            name='resume',
            field=models.FileField(blank=True, default=None, null=True, upload_to='StudentResume'),
        ),
    ]
