# Generated by Django 5.2.5 on 2025-08-30 05:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_alter_studentdetails_resume'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentdetails',
            name='company_location',
        ),
        migrations.RemoveField(
            model_name='studentdetails',
            name='company_name',
        ),
        migrations.RemoveField(
            model_name='studentdetails',
            name='job_title',
        ),
        migrations.RemoveField(
            model_name='studentdetails',
            name='salary',
        ),
        migrations.CreateModel(
            name='JobInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(blank=True, max_length=100, null=True)),
                ('company_name', models.CharField(blank=True, max_length=100, null=True)),
                ('company_location', models.CharField(blank=True, max_length=100, null=True)),
                ('salary', models.FloatField(blank=True, null=True)),
                ('date', models.DateField()),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_info', to='student.studentdetails')),
            ],
        ),
    ]
