# Generated by Django 5.2.5 on 2025-12-27 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_remove_studentdetails_company_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobinfo',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
