# Generated by Django 5.2.5 on 2025-12-31 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0006_alter_jobinfo_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentdetails',
            name='is_passed_out',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
