# Generated by Django 5.2.5 on 2026-03-26 04:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0007_studentdetails_is_passed_out'),
    ]

    operations = [
        migrations.CreateModel(
            name='SemesterGrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester_name', models.CharField(max_length=100)),
                ('sgpa', models.FloatField()),
                ('total_credits', models.FloatField()),
                ('date_added', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='semester_grades', to='student.studentdetails')),
            ],
            options={
                'unique_together': {('student', 'semester_name')},
            },
        ),
    ]
